name: Generate Release Note

on:
  push:
    tags:
      - '*'
permissions:
  contents: write
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"
          cache: npm
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: 'true'
      - name: Install dependencies
        run: npm install
      - name: Generate Libraries
        run: npm run build
      - name: Generate a changelog
        run: npx git-cliff --latest --strip header > ${{ github.workspace }}-CHANGELOG.txt
      - name: Archive Release
        uses: thedoctor0/zip-release@0.7.6
        with:
          type: 'zip'
          filename: 'tribute.zip'
          directory: './dist/'
      - name: Generate release note
        uses: softprops/action-gh-release@v2
        with:
          body_path: ${{ github.workspace }}-CHANGELOG.txt
          generate_release_notes: true
          files: 'dist/tribute.zip'
